# ===================================================================
# Spring Boot configuration for the "cloudfoundry" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        prefer-ip-address: false
        hostname: ${vcap.application.uris[0]}
        nonSecurePort: 80
logging:
    level:
        com.bmcd.asset.health.uaa: DEBUG
        io.github.jhipster: DEBUG
        com.netflix.discovery: DEBUG
spring:
    data:
        jest:
             uri: https://cloudfoundry:3ac6c0902d80cab651dd976c5b2958db@thorin-us-east-1.searchly.com
liquibase:
        contexts: demo
